# -*- coding: utf-8 -*-
"""A_Comparative_Analysis_of_Multi_Class_Price_Range_Based_on_E_Commerce_RAM_Pricing_Intelligence_2026_on_eBay_Listings.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16Bo4Cu9TsJGzwJu9jZtl8wJviJd--NC4

## 1. Setup & Imports <a id='1-setup'></a>
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import matplotlib.gridspec as gridspec
import seaborn as sns
import warnings
warnings.filterwarnings("ignore")
from sklearn.model_selection import (train_test_split, StratifiedKFold, cross_val_score, GridSearchCV, learning_curve)
from sklearn.preprocessing import (LabelEncoder, StandardScaler, OneHotEncoder, label_binarize)
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.impute import SimpleImputer
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier, plot_tree
from sklearn.ensemble import RandomForestClassifier
from sklearn.neural_network import MLPClassifier
from sklearn.svm import SVC
from sklearn.metrics import (accuracy_score, precision_score, recall_score, f1_score, roc_auc_score, roc_curve, confusion_matrix, classification_report, ConfusionMatrixDisplay, precision_recall_curve, average_precision_score)
try:
    from imblearn.over_sampling import SMOTE
    SMOTE_AVAILABLE = True
except ImportError:
    SMOTE_AVAILABLE = False
plt.rcParams.update({'figure.facecolor': 'white','axes.facecolor': '#f8f9fa','axes.grid': True,'grid.alpha': 0.4,'font.size': 11,'axes.titlesize': 13,'axes.labelsize': 11,})
PALETTE = ['#2E86AB', '#E84855', '#3BB273', '#F18F01', '#7B2D8B']
SEED = 42
np.random.seed(SEED)
print("All libraries loaded successfully.")

"""## 2. Data Loading & Initial Inspection <a id='2-loading'></a>"""

df = pd.read_csv("/content/ram_pricing_intelligence_2026.csv")
print(f"Dataset shape: {df.shape[0]:,} rows × {df.shape[1]} columns")
print("\n── Column list ──")
for c in df.columns:
    print(f"  {c:<20} dtype: {df[c].dtype}")

df.head(5)

display(df.describe(include='number').round(2))
print()
cat_cols = df.select_dtypes('object').columns.tolist()
for c in cat_cols:
    print(f"  {c:<20} {df[c].nunique():>4} unique  | top: {df[c].value_counts().index[0]}")

"""## 3. Exploratory Data Analysis (EDA) <a id='3-eda'></a>

Deep analysis of **price distribution**, **price category (Budget / Mid-Range / Premium)** segmentation, and how every feature relates to pricing behaviour.
"""

fig = plt.figure(figsize=(20, 12))
gs  = gridspec.GridSpec(2, 3, figure=fig, hspace=0.45, wspace=0.35)
ax1 = fig.add_subplot(gs[0, 0])
ax1.hist(df['price'].dropna(), bins=100, color=PALETTE[0], edgecolor='white', alpha=0.8, density=True)
from scipy.stats import gaussian_kde
kde_x = np.linspace(0, df['price'].quantile(0.99), 300)
kde = gaussian_kde(df['price'].dropna())(kde_x)
ax1.plot(kde_x, kde, color=PALETTE[1], lw=2)
ax1.set_title("Price (raw) — Histogram + KDE")
ax1.set_xlabel("Price (USD)")
ax1.set_ylabel("Density")
ax2 = fig.add_subplot(gs[0, 1])
log_p = np.log1p(df['price'].dropna())
ax2.hist(log_p, bins=80, color=PALETTE[2], edgecolor='white', alpha=0.8, density=True)
kde2  = gaussian_kde(log_p)(np.linspace(log_p.min(), log_p.max(), 300))
ax2.plot(np.linspace(log_p.min(), log_p.max(), 300), kde2, color=PALETTE[1], lw=2)
ax2.set_title("log(1+Price) — Histogram + KDE")
ax2.set_xlabel("log(1 + Price)")
ax3 = fig.add_subplot(gs[0, 2])
sorted_p = np.sort(df['price'].dropna())
ax3.plot(sorted_p, np.arange(1, len(sorted_p)+1)/len(sorted_p), color=PALETTE[3], lw=2)
for q, ls in [(0.25,'--'),(0.50,'-.'),(0.75,':')]:
    val = np.quantile(sorted_p, q)
    ax3.axvline(val, linestyle=ls, color='grey', alpha=0.7, label=f"Q{int(q*100)}={val:.0f}")
ax3.set_xlim(0, df['price'].quantile(0.98))
ax3.set_title("Empirical CDF (trimmed at p98)")
ax3.set_xlabel("Price (USD)")
ax3.set_ylabel("Cumulative fraction")
ax3.legend(fontsize=9)
df_plot = df.copy()
df_plot['price_range'] = pd.qcut(df_plot['price'], q=3, labels=['Budget','Mid-Range','Premium'])
ax4 = fig.add_subplot(gs[1, 0])
order = ['Budget','Mid-Range','Premium']
for i, cat in enumerate(order):
    sub = df_plot[df_plot['price_range']==cat]['price']
    ax4.boxplot(sub, positions=[i], widths=0.5, patch_artist=True, boxprops=dict(facecolor=PALETTE[i], alpha=0.7),medianprops=dict(color='black', lw=2), flierprops=dict(marker='.', markersize=3, alpha=0.3))
ax4.set_xticks([0,1,2]); ax4.set_xticklabels(order)
ax4.set_title("Box Plot by Price Category")
ax4.set_ylabel("Price (USD)")
ax5 = fig.add_subplot(gs[1, 1])
data_v = [df_plot[df_plot['price_range']==c]['price'].dropna().values for c in order]
parts = ax5.violinplot(data_v, positions=[0,1,2], showmedians=True, showextrema=True)
for i, body in enumerate(parts['bodies']):
    body.set_facecolor(PALETTE[i]); body.set_alpha(0.7)
parts['cmedians'].set_color('black')
ax5.set_xticks([0,1,2]); ax5.set_xticklabels(order)
ax5.set_title("Violin Plot by Price Category")
ax5.set_ylabel("Price (USD)")
ax6 = fig.add_subplot(gs[1, 2])
counts = df_plot['price_range'].value_counts().reindex(order)
avgs   = df_plot.groupby('price_range', observed=True)['price'].mean().reindex(order)
bars = ax6.bar(order, counts.values, color=PALETTE[:3], edgecolor='white', alpha=0.85)
ax6_r = ax6.twinx()
ax6_r.plot(order, avgs.values, 'D--', color=PALETTE[3], lw=2, markersize=8, label='Avg Price')
ax6.set_title("Category Count & Avg Price")
ax6.set_ylabel("Count")
ax6_r.set_ylabel("Avg Price (USD)")
ax6_r.legend(loc='upper left', fontsize=9)
for bar, cnt in zip(bars, counts.values):
    ax6.text(bar.get_x()+bar.get_width()/2, bar.get_height()+5, f"{cnt:,}", ha='center', fontsize=9)
plt.suptitle("Price Distribution — Overview", fontsize=15, fontweight='bold', y=1.01)
plt.savefig("eda1_price_distribution.png", dpi=150, bbox_inches='tight')
plt.show()

from scipy.stats import gaussian_kde as gkde
df2 = df.copy()
df2['price_range'] = pd.qcut(df2['price'], q=3, labels=['Budget','Mid-Range','Premium'])
df2['log_price']   = np.log1p(df2['price'])
fig, axes = plt.subplots(2, 3, figsize=(23, 10))
fig.subplots_adjust(hspace=0.42, wspace=0.32)
order = ['Budget','Mid-Range','Premium']
ax = axes[0, 0]
for i, cat in enumerate(order):
    sub = df2[df2['price_range']==cat]
    ax.scatter(sub['capacity_gb'], sub['log_price'], alpha=0.35, s=18, c=PALETTE[i], label=cat)
ax.set_title("Capacity GB vs log(Price)")
ax.set_xlabel("Capacity (GB)")
ax.set_ylabel("log(1+Price)")
ax.legend(fontsize=9)
ax = axes[0, 1]
df2['cap_bin'] = pd.cut(df2['capacity_gb'], bins=[0,8,16,32,64,128,256,512,np.inf], labels=['≤8','9-16','17-32','33-64','65-128','129-256','257-512','>512'])
med = df2.groupby('cap_bin', observed=True)['price'].median()
ax.bar(med.index, med.values, color=PALETTE[0], edgecolor='white', alpha=0.85)
ax.set_title("Median Price by Capacity Bin")
ax.set_xlabel("Capacity (GB)")
ax.set_ylabel("Median Price (USD)")
for i,(l,v) in enumerate(med.items()):
    ax.text(i, v+4, f"${v:.0f}", ha='center', fontsize=8)
ax = axes[0, 2]
heat = df2.pivot_table(index='cap_bin', columns='ram_generation', values='price', aggfunc='median', observed=True)
im = ax.imshow(heat.values, cmap='YlOrRd', aspect='auto')
ax.set_xticks(range(len(heat.columns))); ax.set_xticklabels(heat.columns)
ax.set_yticks(range(len(heat.index)));   ax.set_yticklabels(heat.index)
plt.colorbar(im, ax=ax, label='Median Price ($)')
for r in range(heat.shape[0]):
    for c in range(heat.shape[1]):
        v = heat.iloc[r, c]
        if not np.isnan(v):
            ax.text(c, r, f"${v:.0f}", ha='center', va='center', fontsize=8)
ax.set_title("Median Price Heatmap\nCapacity × RAM Gen")
ax = axes[1, 0]
df2['price_per_gb'] = df2['price'] / df2['capacity_gb'].replace(0, np.nan)
data_ppg = [df2[df2['price_range']==c]['price_per_gb'].dropna().values for c in order]
bp = ax.boxplot(data_ppg, positions=[0,1,2], widths=0.5,
                patch_artist=True, showfliers=False, medianprops=dict(color='black', lw=2))
for patch, color in zip(bp['boxes'], PALETTE[:3]):
    patch.set_facecolor(color); patch.set_alpha(0.75)
ax.set_xticks([0,1,2]); ax.set_xticklabels(order)
ax.set_title("Price-per-GB Distribution by Category")
ax.set_ylabel("USD / GB")
ax = axes[1, 1]
for i, cat in enumerate(order):
    sub = df2[df2['price_range']==cat].dropna(subset=['capacity_gb','price_per_gb'])
    ax.scatter(sub['capacity_gb'], sub['price_per_gb'], alpha=0.35, s=16, c=PALETTE[i], label=cat)
ax.set_title("Capacity vs Price-per-GB")
ax.set_xlabel("Capacity (GB)")
ax.set_ylabel("Price / GB (USD)")
ax.legend(fontsize=9)
ax.set_ylim(0, df2['price_per_gb'].quantile(0.97))
ax = axes[1, 2]
comp = df2.groupby(['cap_bin','price_range'], observed=True).size().unstack(fill_value=0)
comp_pct = comp.div(comp.sum(axis=1), axis=0) * 100
bottom = np.zeros(len(comp_pct))
for i, cat in enumerate(order):
    if cat in comp_pct.columns:
        ax.bar(range(len(comp_pct)), comp_pct[cat], bottom=bottom, label=cat, color=PALETTE[i], edgecolor='white', alpha=0.85)
        bottom += comp_pct[cat].values
ax.set_xticks(range(len(comp_pct))); ax.set_xticklabels(comp_pct.index, rotation=35, ha='right')
ax.set_title("Price Tier Mix by Capacity Bin (%)")
ax.set_ylabel("% of listings")
ax.legend(fontsize=9, loc='upper right')
plt.suptitle("Price vs Capacity Deep Dive", fontsize=15, fontweight='bold', y=1.01)
plt.savefig("eda2_price_capacity.png", dpi=150, bbox_inches='tight')
plt.show()

df3 = df.copy()
df3['price_range'] = pd.qcut(df3['price'], q=3, labels=['Budget','Mid-Range','Premium'])
df3['log_price']   = np.log1p(df3['price'])
order = ['Budget','Mid-Range','Premium']
fig, axes = plt.subplots(2, 3, figsize=(23, 10))
fig.subplots_adjust(hspace=0.45, wspace=0.35)
ax = axes[0, 0]
ct = df3.groupby(['ram_generation','price_range'], observed=True).size().unstack(fill_value=0)
x  = np.arange(len(ct)); w = 0.25
for i, cat in enumerate(order):
    if cat in ct.columns:
        ax.bar(x + i*w, ct[cat], w, label=cat, color=PALETTE[i], edgecolor='white', alpha=0.85)
ax.set_xticks(x + w); ax.set_xticklabels(ct.index)
ax.set_title("RAM Generation × Price Category")
ax.set_ylabel("Count"); ax.legend(fontsize=9)
ax = axes[0, 1]
gens = [g for g in df3['ram_generation'].unique() if df3['ram_generation'].eq(g).sum()>5]
data_v = [df3[df3['ram_generation']==g]['log_price'].dropna().values for g in gens]
parts = ax.violinplot(data_v, positions=range(len(gens)), showmedians=True)
for i, body in enumerate(parts['bodies']):
    body.set_facecolor(PALETTE[i % len(PALETTE)]); body.set_alpha(0.7)
parts['cmedians'].set_color('black')
ax.set_xticks(range(len(gens))); ax.set_xticklabels(gens)
ax.set_title("log(Price) Distribution by RAM Generation")
ax.set_ylabel("log(1+Price)")
ax = axes[0, 2]
for i, cat in enumerate(order):
    sub = df3[df3['price_range']==cat].dropna(subset=['bus_speed_mhz','log_price'])
    ax.scatter(sub['bus_speed_mhz'], sub['log_price'],
               alpha=0.3, s=15, c=PALETTE[i], label=cat)
    if len(sub) > 10:
        z = np.polyfit(sub['bus_speed_mhz'], sub['log_price'], 1)
        xs = np.linspace(sub['bus_speed_mhz'].min(), sub['bus_speed_mhz'].max(), 100)
        ax.plot(xs, np.poly1d(z)(xs), color=PALETTE[i], lw=1.8, ls='--')
ax.set_title("Bus Speed vs log(Price) by Category")
ax.set_xlabel("Bus Speed (MHz)")
ax.set_ylabel("log(1+Price)")
ax.legend(fontsize=9)
ax = axes[1, 0]
cond_order = ['New','Used','Open box','Excellent - Refurbished', 'Very Good - Refurbished','For parts or not working']
heat2 = df3.pivot_table(index='condition', columns='price_range', values='price', aggfunc='median', observed=True).reindex(cond_order).reindex(columns=order)
im2 = ax.imshow(heat2.values, cmap='Blues', aspect='auto')
plt.colorbar(im2, ax=ax, label='Median Price ($)')
ax.set_xticks(range(len(order))); ax.set_xticklabels(order, fontsize=9)
ax.set_yticks(range(len(cond_order))); ax.set_yticklabels(cond_order, fontsize=8)
for r in range(heat2.shape[0]):
    for c in range(heat2.shape[1]):
        v = heat2.iloc[r, c]
        if not np.isnan(v):
            ax.text(c, r, f"${v:.0f}", ha='center', va='center', fontsize=8)
ax.set_title("Median Price Heatmap\nCondition × Price Category")
ax = axes[1, 1]
ut_ct = df3.groupby(['unit_type','price_range'], observed=True).size().unstack(fill_value=0)
ut_pct = ut_ct.div(ut_ct.sum(axis=1), axis=0) * 100
bottom = np.zeros(len(ut_pct))
for i, cat in enumerate(order):
    if cat in ut_pct.columns:
        bars = ax.bar(range(len(ut_pct)), ut_pct[cat], bottom=bottom, label=cat, color=PALETTE[i], edgecolor='white', alpha=0.85)
        for j, (b, h) in enumerate(zip(bottom, ut_pct[cat].values)):
            if h > 8:
                ax.text(j, b + h/2, f"{h:.0f}%", ha='center', va='center', fontsize=9, color='white', fontweight='bold')
        bottom += ut_pct[cat].values
ax.set_xticks(range(len(ut_pct))); ax.set_xticklabels(ut_pct.index)
ax.set_title("Price Tier Mix by Unit Type (%)")
ax.set_ylabel("% of listings"); ax.legend(fontsize=9)
ax = axes[1, 2]
data_bs = [df3[df3['price_range']==c]['bus_speed_mhz'].dropna().values for c in order]
bp = ax.boxplot(data_bs, positions=[0,1,2], widths=0.5, patch_artist=True, showfliers=False, medianprops=dict(color='black', lw=2))
for patch, color in zip(bp['boxes'], PALETTE[:3]):
    patch.set_facecolor(color); patch.set_alpha(0.75)
ax.set_xticks([0,1,2]); ax.set_xticklabels(order)
ax.set_title("Bus Speed (MHz) by Price Category")
ax.set_ylabel("Bus Speed (MHz)")
plt.suptitle("Price Category vs RAM Specs & Listing Attributes", fontsize=15, fontweight='bold', y=1.01)
plt.savefig("eda3_specs_vs_tier.png", dpi=150, bbox_inches='tight')
plt.show()

df4 = df.copy()
df4['price_range'] = pd.qcut(df4['price'], q=3, labels=['Budget','Mid-Range','Premium'])
df4['log_price']   = np.log1p(df4['price'])
order = ['Budget','Mid-Range','Premium']
TOP_N = 12
top_brands = df4['brand'].value_counts().head(TOP_N).index.tolist()
df4_top = df4[df4['brand'].isin(top_brands)]
fig, axes = plt.subplots(2, 3, figsize=(23, 10))
fig.subplots_adjust(hspace=0.48, wspace=0.38)
ax = axes[0, 0]
brand_med = df4_top.groupby('brand')['price'].median().sort_values(ascending=True)
majority_tier = (df4_top.groupby(['brand','price_range'], observed=True).size().unstack(fill_value=0).idxmax(axis=1))
colors_bar = [PALETTE[order.index(majority_tier.get(b,'Budget'))] for b in brand_med.index]
bars = ax.barh(brand_med.index, brand_med.values, color=colors_bar, edgecolor='white', alpha=0.85)
ax.set_title("Median Price by Brand\n(colour = majority tier)")
ax.set_xlabel("Median Price (USD)")
for bar, v in zip(bars, brand_med.values):
    ax.text(v+2, bar.get_y()+bar.get_height()/2, f"${v:.0f}", va='center', fontsize=8)
ax = axes[0, 1]
b_ct  = (df4_top.groupby(['brand','price_range'], observed=True).size().unstack(fill_value=0).reindex(columns=order, fill_value=0))
b_pct = b_ct.div(b_ct.sum(axis=1), axis=0) * 100
b_pct_s = b_pct.loc[brand_med.index]
bottom = np.zeros(len(b_pct_s))
for i, cat in enumerate(order):
    ax.barh(range(len(b_pct_s)), b_pct_s[cat], left=bottom, label=cat, color=PALETTE[i], edgecolor='white', alpha=0.85)
    bottom += b_pct_s[cat].values
ax.set_yticks(range(len(b_pct_s))); ax.set_yticklabels(b_pct_s.index, fontsize=9)
ax.set_title("Price Tier Mix by Brand (%)")
ax.set_xlabel("% of listings"); ax.legend(fontsize=9, loc='lower right')
ax = axes[0, 2]
brand_order_box = brand_med.index.tolist()[::-1]
data_bx = [df4_top[df4_top['brand']==b]['price'].dropna().values for b in brand_order_box]
bp = ax.boxplot(data_bx, vert=False, patch_artist=True, showfliers=False, medianprops=dict(color='black', lw=2))
for i, (patch, b) in enumerate(zip(bp['boxes'], brand_order_box)):
    tier = majority_tier.get(b, 'Budget')
    patch.set_facecolor(PALETTE[order.index(tier)]); patch.set_alpha(0.7)
ax.set_yticks(range(1, len(brand_order_box)+1))
ax.set_yticklabels(brand_order_box, fontsize=9)
ax.set_title("Price Distribution per Brand (box)")
ax.set_xlabel("Price (USD)")
ax = axes[1, 0]
brand_stats = df4_top.groupby('brand', observed=True).agg(median_price=('price','median'),count=('price','count'),std_price=('price','std')).fillna(0)
sc = ax.scatter(brand_stats['count'], brand_stats['median_price'],s=brand_stats['count']*1.5, alpha=0.65,c=[PALETTE[order.index(majority_tier.get(b,'Budget'))]
                   for b in brand_stats.index], edgecolors='white', linewidths=0.8)
for b, row in brand_stats.iterrows():
    ax.annotate(b, (row['count'], row['median_price']), fontsize=7.5, ha='left', va='bottom',xytext=(3,3), textcoords='offset points')
ax.set_title("Listing Count vs Median Price\n(bubble size = count)")
ax.set_xlabel("# Listings"); ax.set_ylabel("Median Price (USD)")
ax = axes[1, 1]
brand_std = brand_stats['std_price'].sort_values(ascending=True)
ax.barh(brand_std.index, brand_std.values,
        color=PALETTE[4], edgecolor='white', alpha=0.8)
ax.set_title("Price Volatility (Std Dev) by Brand")
ax.set_xlabel("Std Deviation of Price (USD)")
for i, v in enumerate(brand_std.values):
    ax.text(v+2, i, f"${v:.0f}", va='center', fontsize=8)
ax = axes[1, 2]
prem_rate = (b_pct['Premium'].sort_values(ascending=True) if 'Premium' in b_pct.columns else pd.Series(dtype=float))
ax.barh(prem_rate.index, prem_rate.values, color=PALETTE[1], edgecolor='white', alpha=0.85)
ax.set_title("Premium Tier Rate by Brand (%)")
ax.set_xlabel("% in Premium tier")
ax.axvline(33.3, color='gray', ls='--', lw=1.2, label="Equal-split baseline")
ax.legend(fontsize=9)
plt.suptitle("Brand × Price Intelligence", fontsize=15, fontweight='bold', y=1.01)
plt.savefig("eda4_brand_price.png", dpi=150, bbox_inches='tight')
plt.show()

df5 = df.copy()
df5['price_range'] = pd.qcut(df5['price'], q=3, labels=['Budget','Mid-Range','Premium'])
df5['demand_ratio'] = df5['sold'] / (df5['available'] + df5['sold'] + 1)
df5['has_discount'] = df5['wasPrice'].notna().astype(int)
df5['discount_pct'] = (df5['wasPrice'] - df5['price']) / df5['wasPrice'] * 100
df5['log_price'] = np.log1p(df5['price'])
order = ['Budget','Mid-Range','Premium']
fig, axes = plt.subplots(2, 3, figsize=(24, 10))
fig.subplots_adjust(hspace=0.45, wspace=0.38)
ax = axes[0, 0]
data_dr = [df5[df5['price_range']==c]['demand_ratio'].dropna().values for c in order]
parts = ax.violinplot(data_dr, positions=[0,1,2], showmedians=True, showextrema=True)
for i, body in enumerate(parts['bodies']):
    body.set_facecolor(PALETTE[i]); body.set_alpha(0.7)
parts['cmedians'].set_color('black')
ax.set_xticks([0,1,2]); ax.set_xticklabels(order)
ax.set_title("Demand Ratio by Price Category\n(sold / (sold+available+1))")
ax.set_ylabel("Demand Ratio")
ax = axes[0, 1]
for i, cat in enumerate(order):
    sub = df5[df5['price_range']==cat].dropna(subset=['sold'])
    ax.scatter(sub['log_price'], np.log1p(sub['sold']),
               alpha=0.35, s=15, c=PALETTE[i], label=cat)
ax.set_title("log(Price) vs log(Sold) by Category")
ax.set_xlabel("log(1+Price)")
ax.set_ylabel("log(1+Sold)")
ax.legend(fontsize=9)
ax = axes[0, 2]
disc_rate = df5.groupby('price_range', observed=True)['has_discount'].mean() * 100
disc_rate = disc_rate.reindex(order)
bars = ax.bar(order, disc_rate.values, color=PALETTE[:3],
              edgecolor='white', alpha=0.85)
ax.set_title("Discount Prevalence by Price Category")
ax.set_ylabel("% of listings with discount")
for bar, v in zip(bars, disc_rate.values):
    ax.text(bar.get_x()+bar.get_width()/2, bar.get_height()+0.2, f"{v:.1f}%", ha='center', fontsize=10)
ax = axes[1, 0]
data_dpm = [df5[(df5['price_range']==c) & df5['discount_pct'].notna()]['discount_pct'].values for c in order]
bp = ax.boxplot(data_dpm, positions=[0,1,2], widths=0.5, patch_artist=True, showfliers=False, medianprops=dict(color='black', lw=2))
for patch, color in zip(bp['boxes'], PALETTE[:3]):
    patch.set_facecolor(color); patch.set_alpha(0.75)
ax.set_xticks([0,1,2]); ax.set_xticklabels(order)
ax.set_title("Discount Depth (%) by Category\n(discounted listings only)")
ax.set_ylabel("Discount %")
ax = axes[1, 1]
data_av = [df5[df5['price_range']==c]['available'].dropna().values for c in order]
bp2 = ax.boxplot(data_av, positions=[0,1,2], widths=0.5, patch_artist=True,
                 showfliers=False, medianprops=dict(color='black', lw=2))
for patch, color in zip(bp2['boxes'], PALETTE[:3]):
    patch.set_facecolor(color); patch.set_alpha(0.75)
ax.set_xticks([0,1,2]); ax.set_xticklabels(order)
ax.set_title("Stock Availability by Price Category")
ax.set_ylabel("Units Available")
ax = axes[1, 2]
disc_df = df5.dropna(subset=['discount_pct'])
for i, cat in enumerate(order):
    sub = disc_df[disc_df['price_range']==cat]
    ax.scatter(sub['price'], sub['discount_pct'], alpha=0.55, s=30, c=PALETTE[i], label=cat, edgecolors='white', linewidths=0.4)
ax.set_title("Price vs Discount Depth (discounted only)")
ax.set_xlabel("Price (USD)")
ax.set_ylabel("Discount (%)")
ax.set_xlim(0, df5['price'].quantile(0.97))
ax.legend(fontsize=9)
plt.suptitle("Demand, Discount & Market Behaviour by Price Category", fontsize=15, fontweight='bold', y=1.01)
plt.savefig("eda5_demand_discount.png", dpi=150, bbox_inches='tight')
plt.show()

from sklearn.ensemble import RandomForestClassifier as RFC
from sklearn.preprocessing import OrdinalEncoder
df6 = df.copy()
df6['price_range'] = pd.qcut(df6['price'], q=3, labels=['Budget','Mid-Range','Premium']).astype(str)
df6['log_price'] = np.log1p(df6['price'])
df6['price_per_gb'] = df6['price'] / df6['capacity_gb'].replace(0, np.nan)
df6['demand_ratio'] = df6['sold'] / (df6['available'] + df6['sold'] + 1)
df6['has_discount'] = df6['wasPrice'].notna().astype(int)
df6['discount_pct'] = ((df6['wasPrice'] - df6['price']) / df6['wasPrice'] * 100).fillna(0)
df6['is_ecc'] = df6['type'].str.upper().str.contains('ECC', na=False).astype(int)
df6['is_sodimm'] = df6['type'].str.upper().str.contains('SODIMM|SO-DIMM', na=False).astype(int)
df6['is_us'] = df6['itemLocation'].str.contains('United States', na=False).astype(int)
df6['is_bulk'] = df6['is_bulk_server']
num_cols_corr = ['price','log_price','capacity_gb','bus_speed_mhz', 'price_per_gb','demand_ratio','has_discount', 'discount_pct','is_ecc','is_sodimm','is_us','is_bulk']
fig, axes = plt.subplots(1, 2, figsize=(23, 8))
fig.subplots_adjust(wspace=0.4)
ax = axes[0]
corr = df6[num_cols_corr].corr()
mask = np.triu(np.ones_like(corr, dtype=bool))
sns.heatmap(corr, mask=mask, annot=True, fmt='.2f', cmap='coolwarm', center=0, ax=ax, linewidths=0.4, annot_kws={'size': 8}, vmin=-1, vmax=1)
ax.set_title("Feature Correlation Matrix\n(all numeric features)", fontsize=13, fontweight='bold')
ax.tick_params(axis='x', rotation=40, labelsize=8)
ax.tick_params(axis='y', labelsize=8)
ax = axes[1]
feat_cols = ['capacity_gb','bus_speed_mhz','price_per_gb','demand_ratio', 'has_discount','discount_pct','is_ecc','is_sodimm','is_us','is_bulk']
df6_clean = df6[feat_cols + ['price_range']].dropna()
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y_enc = le.fit_transform(df6_clean['price_range'])
X_fi  = df6_clean[feat_cols].fillna(df6_clean[feat_cols].median())
rf_fi = RFC(n_estimators=200, max_depth=8, random_state=SEED, n_jobs=-1)
rf_fi.fit(X_fi, y_enc)
imp = pd.Series(rf_fi.feature_importances_, index=feat_cols).sort_values(ascending=True)
colors_fi = [PALETTE[0] if v < imp.median() else PALETTE[1] for v in imp.values]
bars = ax.barh(imp.index, imp.values, color=colors_fi, edgecolor='white', alpha=0.85)
ax.axvline(imp.median(), color='grey', ls='--', lw=1.2, label='Median importance')
ax.set_title("Feature Importance for Price Category\n(Random Forest, n=200 trees)", fontsize=13, fontweight='bold')
ax.set_xlabel("Importance Score")
ax.legend(fontsize=9)
for bar, v in zip(bars, imp.values):
    ax.text(v+0.001, bar.get_y()+bar.get_height()/2, f"{v:.3f}", va='center', fontsize=9)
plt.suptitle("Correlations & Feature Importance vs Price Category", fontsize=15, fontweight='bold', y=1.01)
plt.savefig("eda6_correlation_importance.png", dpi=150, bbox_inches='tight')
plt.show()
print("\n── Top predictors of price category (by RF importance) ──")
for feat, score in imp.sort_values(ascending=False).items():
    print(f"  {feat:<20} {score:.4f}")

"""## 4. Data Preprocessing & Feature Engineering <a id='4-preprocessing'></a>"""

df_ml = df.copy()
df_ml['log_price'] = np.log1p(df_ml['price'])
df_ml['discount_amount'] = df_ml['wasPrice'] - df_ml['price']
df_ml['has_discount'] = df_ml['wasPrice'].notna().astype(int)
df_ml['price_per_gb'] = df_ml['price'] / df_ml['capacity_gb'].replace(0, np.nan)
df_ml['log_price_per_gb'] = np.log1p(df_ml['price_per_gb'])
df_ml['demand_ratio'] = df_ml['sold'] / (df_ml['available'] + df_ml['sold'] + 1)
df_ml['is_ecc'] = df_ml['type'].str.upper().str.contains('ECC', na=False).astype(int)
df_ml['is_sodimm'] = df_ml['type'].str.upper().str.contains('SODIMM|SO-DIMM', na=False).astype(int)
df_ml['is_gaming'] = df_ml['type'].str.upper().str.contains('GAMING|RGB|TRIDENT|RIPJAWS|FURY|VENGEANCE', na=False).astype(int)
df_ml['is_us_listing'] = df_ml['itemLocation'].str.contains('United States', na=False).astype(int)
cond_map = {'New': 'New', 'Open box': 'Open box', 'Used': 'Used', 'Excellent - Refurbished': 'Refurbished', 'Very Good - Refurbished': 'Refurbished', 'For parts or not working': 'Parts Only'}
df_ml['condition_clean'] = df_ml['condition'].map(cond_map).fillna('Unknown')
print("Feature engineering complete.")
new_feats = ['discount_amount', 'has_discount', 'price_per_gb', 'demand_ratio', 'is_ecc', 'is_sodimm', 'is_gaming', 'is_us_listing', 'condition_clean']
for f in new_feats:
    print(f"  + {f}")

df_ml['price_range'] = pd.qcut(df_ml['price'],q=3, labels=['Budget', 'Mid-Range', 'Premium']).astype(str)
NUMERICAL_FEATURES = ['capacity_gb', 'bus_speed_mhz', 'demand_ratio', 'has_discount']
CATEGORICAL_FEATURES = ['ram_generation', 'condition_clean', 'unit_type', 'brand']
BINARY_FEATURES = ['is_ecc', 'is_sodimm', 'is_gaming', 'is_us_listing', 'is_bulk_server']
ALL_FEATURES = NUMERICAL_FEATURES + CATEGORICAL_FEATURES + BINARY_FEATURES
TARGET = 'price_range'
model_df = df_ml[ALL_FEATURES + [TARGET]].copy()
model_df = model_df.dropna(subset=['capacity_gb'])
print(f"Modelling dataframe shape: {model_df.shape}")
X = model_df.drop(columns=[TARGET])
y = model_df[TARGET]
print(f"\nFeature matrix: {X.shape}")
print(f"Target vector:  {y.shape}")
print(f"\nClass distribution:\n{y.value_counts().to_string()}")

num_pipeline = Pipeline([('imputer', SimpleImputer(strategy='median')),('scaler', StandardScaler())])
cat_pipeline = Pipeline([('imputer', SimpleImputer(strategy='most_frequent')),('ohe', OneHotEncoder(handle_unknown='ignore', sparse_output=False))])
preprocessor = ColumnTransformer(transformers=[('num', num_pipeline, NUMERICAL_FEATURES),('cat', cat_pipeline, CATEGORICAL_FEATURES),('bin', 'passthrough', BINARY_FEATURES)], remainder='drop')
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20, random_state=SEED, stratify=y)
X_train_proc = preprocessor.fit_transform(X_train)
X_test_proc  = preprocessor.transform(X_test)
print(f"Train set: {X_train_proc.shape}  |  Test set: {X_test_proc.shape}")
print(f"Train class balance: {dict(zip(*np.unique(y_train, return_counts=True)))}")
print(f"Test  class balance: {dict(zip(*np.unique(y_test,  return_counts=True)))}")

"""## 5. Class Imbalance Handling <a id='5-imbalance'></a>

The dataset exhibits ~11:1 class imbalance. We apply **SMOTE** (Synthetic Minority Over-sampling Technique) on the training set to generate synthetic samples for the minority class. The test set remains untouched to ensure unbiased evaluation.
"""

if SMOTE_AVAILABLE:
    smote = SMOTE(random_state=SEED)
    X_train_bal, y_train_bal = smote.fit_resample(X_train_proc, y_train)
else:
    print("imblearn not available — using class_weight='balanced' in models")
    X_train_bal, y_train_bal = X_train_proc, y_train
from collections import Counter
fig, axes = plt.subplots(1, 2, figsize=(12, 4))
before_counts = Counter(y_train)
axes[0].bar(before_counts.keys(), before_counts.values())
axes[0].set_title("Before SMOTE")
axes[0].set_ylabel("Count")
after_counts = Counter(y_train_bal)
axes[1].bar(after_counts.keys(), after_counts.values())
axes[1].set_title("After SMOTE")
plt.tight_layout()
plt.show()

"""## 6. Model Training <a id='6-training'></a>


"""

results = {}
def evaluate_model(name, model, X_tr, y_tr, X_te, y_te):
    model.fit(X_tr, y_tr)
    y_pred = model.predict(X_te)
    if hasattr(model, 'predict_proba'):
        y_prob = model.predict_proba(X_te)
    else:
        y_prob = model.decision_function(X_te)
    acc = accuracy_score(y_te, y_pred)
    prec = precision_score(y_te, y_pred, average='weighted', zero_division=0)
    rec = recall_score(y_te, y_pred, average='weighted', zero_division=0)
    f1 = f1_score(y_te, y_pred, average='weighted', zero_division=0)
    auc = roc_auc_score(y_te, y_prob, multi_class='ovr', average='weighted')
    ap = average_precision_score(label_binarize(y_te, classes=model.classes_), y_prob, average='weighted')
    cm = confusion_matrix(y_te, y_pred)
    cv_f1 = cross_val_score(model, X_tr, y_tr, cv=5, scoring='f1_weighted', n_jobs=-1).mean()
    results[name] = {'model': model, 'y_pred': y_pred, 'y_prob': y_prob,'accuracy': acc, 'precision': prec, 'recall': rec,'f1': f1, 'roc_auc': auc, 'avg_precision': ap,'cv_f1': cv_f1, 'confusion_matrix': cm}
    print(f"  {name:<30} Acc={acc:.3f}  Prec={prec:.3f}  Rec={rec:.3f}  "
          f"F1={f1:.3f}  AUC={auc:.3f}  CV-F1={cv_f1:.3f}")
    return model

"""### 6.1 Logistic Regression"""

lr_param_grid = {'C': [1000]}
lr_gs = GridSearchCV(LogisticRegression(max_iter=500, solver='lbfgs', random_state=SEED), param_grid=lr_param_grid, scoring='f1_weighted', cv=5, n_jobs=-1)
lr_gs.fit(X_train_bal, y_train_bal)
best_lr = lr_gs.best_estimator_
evaluate_model("Logistic Regression", best_lr, X_train_bal, y_train_bal, X_test_proc, y_test)

"""**Tuning History**

**Tune 1:**

**LogisticRegression(C=0.01, max_iter=1000, random_state=42)**

**Logistic Regression Accuracy=0.728  Precision=0.722  Recall=0.728  F1 Score=0.714  AUC=0.902  CV-F1=0.724**

**Tune 2:**

**LogisticRegression(C=0.1, max_iter=1000, random_state=42)**

**Logistic Regression Accuracy=0.803  Precision=0.800  Recall=0.803  F1 Scoore=0.800  AUC=0.934  CV-F1=0.797**

**Tune 3:**

**LogisticRegression(C=10, max_iter=1000, random_state=42)**

**Logistic Regression Accuracy=0.836  Precision=0.836  Recall=0.836  F1 Score=0.836  AUC=0.947  CV-F1=0.857**

**Tune 4:**

**LogisticRegression(C=1000, max_iter=500, random_state=42)**

**Logistic Regression Accuracy=0.860  Precision=0.860  Recall=0.860  F1 Score=0.860  AUC=0.946  CV-F1=0.871**

**Tune 5:**

**LogisticRegression(C=1000, max_iter=500, random_state=42, solver="saga")**

**Logistic Regression Accuracy=0.838  Precision=0.838  Recall=0.838  F1 Score=0.838  AUC=0.947 CV-F1=0.855**

### 6.2 Decision Tree
"""

dt_param_grid = {'max_depth': [20],'min_samples_leaf': [20],'criterion': ['gini', 'entropy']}
dt_gs = GridSearchCV(DecisionTreeClassifier(random_state=SEED), param_grid=dt_param_grid, scoring='f1_weighted', cv=5, n_jobs=-1)
dt_gs.fit(X_train_bal, y_train_bal)
best_dt = dt_gs.best_estimator_
print(f"  Best params: {dt_gs.best_params_}")
evaluate_model("Decision Tree", best_dt, X_train_bal, y_train_bal, X_test_proc, y_test)

"""**Tuning History**

**Tune 1:**

**DecisionTreeClassifier(max_depth=2, min_samples_leaf=5, random_state=42)**

**Decision Tree Acc=0.808  Prec=0.817  Rec=0.808  F1=0.810  AUC=0.893  CV-F1=0.827**

**Tune 2:**

**DecisionTreeClassifier(criterion='entropy', max_depth=20, min_samples_leaf=10,
                       random_state=42)**

**Decision Tree                  Acc=0.860  Prec=0.862  Rec=0.860  F1=0.860  AUC=0.952  CV-F1=0.867**

**Tune 3:**

**DecisionTreeClassifier(criterion='entropy', max_depth=50, min_samples_leaf=80,
                       random_state=42)**

**Decision Tree                  Acc=0.829  Prec=0.829  Rec=0.829  F1=0.828  AUC=0.938  CV-F1=0.834**

**Tune 4:**

**DecisionTreeClassifier(max_depth=20, min_samples_leaf=20, random_state=42)**

**Decision Tree                  Acc=0.860  Prec=0.863  Rec=0.860  F1=0.861  AUC=0.955  CV-F1=0.862**

### 6.3 Random Forest
"""

rf_param_grid = {'n_estimators': [200], 'max_depth': [None], 'min_samples_split': [5], 'min_samples_leaf': [1], 'max_features': ['sqrt'], 'bootstrap': [True]}
rf_gs = GridSearchCV(RandomForestClassifier(random_state=SEED, n_jobs=-1), param_grid=rf_param_grid, scoring='f1_weighted', cv=5, n_jobs=-1)
rf_gs.fit(X_train_bal, y_train_bal)
best_rf = rf_gs.best_estimator_
print(f"  Best params: {rf_gs.best_params_}")
evaluate_model("Random Forest", best_rf, X_train_bal, y_train_bal, X_test_proc, y_test)

"""**Tuning History**

**Tune 1:**

**RandomForestClassifier(max_depth=10, min_samples_leaf=4, min_samples_split=10,
                       n_estimators=200, n_jobs=-1, random_state=42)**

**Random Forest                  Acc=0.806  Prec=0.804  Rec=0.806  F1=0.803  AUC=0.949  CV-F1=0.837**

**Tune 2:**

**RandomForestClassifier(max_depth=30, min_samples_leaf=8, min_samples_split=12,
                       n_estimators=400, n_jobs=-1, random_state=42)**

**Random Forest                  Acc=0.791  Prec=0.788  Rec=0.791  F1=0.786  AUC=0.944  CV-F1=0.822**

**Tune 3:**

**RandomForestClassifier(min_samples_split=5, n_estimators=200, n_jobs=-1,
                       random_state=42)**

**Random Forest                  Acc=0.862  Prec=0.862  Rec=0.862  F1=0.862  AUC=0.962  CV-F1=0.887**

**Tune 4:**

**RandomForestClassifier(max_depth=20, min_samples_split=10, n_estimators=400,
                       n_jobs=-1, random_state=42)**

**Random Forest                  Acc=0.850  Prec=0.850  Rec=0.850  F1=0.850  AUC=0.962  CV-F1=0.879**

### 6.4 MLP Neural Network
"""

mlp_param_grid = {'hidden_layer_sizes': [(256, 128)],'activation': ['relu'],'solver': ['sgd'],'alpha': [0.001],'learning_rate_init': [0.001],'learning_rate': ['constant', 'adaptive']}
mlp_gs = GridSearchCV(MLPClassifier(max_iter=800, random_state=SEED, n_iter_no_change=15, validation_fraction=0.1), param_grid=mlp_param_grid, scoring='f1_weighted', cv=5, n_jobs=-1)
mlp_gs.fit(X_train_bal, y_train_bal)
best_mlp = mlp_gs.best_estimator_
print(f"  Best params: {mlp_gs.best_params_}")
evaluate_model("MLP Neural Network", best_mlp, X_train_bal, y_train_bal, X_test_proc, y_test)

"""**Tuning History**

**Tune 1:**

**MLPClassifier(activation='tanh', alpha=0.001, hidden_layer_sizes=(256, 128, 64),
              max_iter=500, n_iter_no_change=15, random_state=42)**

**MLP Neural Network             Acc=0.857  Prec=0.857  Rec=0.857  F1=0.857  AUC=0.943  CV-F1=0.879**

**Tune 2:**

**MLPClassifier(alpha=0.01, hidden_layer_sizes=(100, 50),
              learning_rate_init=0.0001, max_iter=500, n_iter_no_change=15,
              random_state=42, solver='sgd')**

**MLP Neural Network             Acc=0.752  Prec=0.751  Rec=0.752  F1=0.740  AUC=0.909  CV-F1=0.727**

**Tune 3:**

**MLPClassifier(alpha=0.001, hidden_layer_sizes=(256, 128), max_iter=500,
              n_iter_no_change=15, random_state=42, solver='sgd')**

**MLP Neural Network             Acc=0.869  Prec=0.869  Rec=0.869  F1=0.869  AUC=0.956  CV-F1=0.877**

### 6.5 Support Vector Machine (SVM)
"""

svm_param_grid = {'C': [100],'gamma': ['auto'],'kernel': ['rbf']}
svm_gs = GridSearchCV(SVC(probability=True, random_state=SEED), param_grid=svm_param_grid, scoring='f1_weighted', cv=5, n_jobs=-1)
svm_gs.fit(X_train_bal, y_train_bal)
best_svm = svm_gs.best_estimator_
print(f"  Best params: {svm_gs.best_params_}")
evaluate_model("SVM", best_svm, X_train_bal, y_train_bal, X_test_proc, y_test)

"""**Tuning History**

**Tune 1:**

**SVC(C=10, gamma='auto', kernel='linear', probability=True, random_state=42)**

**SVM                            Acc=0.859  Prec=0.858  Rec=0.859  F1=0.858  AUC=0.944  CV-F1=0.867**

**Tune 2:**

**SVC(C=10, probability=True, random_state=42)**

 **SVM                            Acc=0.857  Prec=0.856  Rec=0.857  F1=0.856  AUC=0.948  CV-F1=0.879**

 **Tune 3:**

 **SVC(C=100, gamma='auto', probability=True, random_state=42)**

 **SVM                            Acc=0.864  Prec=0.864  Rec=0.864  F1=0.864  AUC=0.945  CV-F1=0.883**

## 7. Model Evaluation & Comparison <a id='7-evaluation'></a>
"""

metrics_df = pd.DataFrame({
    name: {
        'Accuracy':  v['accuracy'],
        'Precision': v['precision'],
        'Recall':    v['recall'],
        'F1 Score':  v['f1'],
        'ROC-AUC':   v['roc_auc'],
        'Avg Precision (PR-AUC)': v['avg_precision'],
        'CV F1 (5-fold)': v['cv_f1']
    }
    for name, v in results.items()}).T.round(4)
display(metrics_df.style.background_gradient(cmap='Greens', axis=0).format("{:.4f}").set_caption(""))
best_model_name = metrics_df['F1 Score'].idxmax()
print(f"\nBest model by F1 Score: {best_model_name}  " f"(F1={metrics_df.loc[best_model_name,'F1 Score']:.4f})")

metric_cols = ['Accuracy', 'Precision', 'Recall', 'F1 Score', 'ROC-AUC']
model_names = list(results.keys())
x = np.arange(len(metric_cols))
width = 0.14
fig, ax = plt.subplots(figsize=(20, 6))
for i, (mname, color) in enumerate(zip(model_names, PALETTE)):
    vals = [metrics_df.loc[mname, col] for col in metric_cols]
    ax.bar(x + i * width, vals, width, label=mname, color=color, edgecolor='white', alpha=0.88)
ax.set_xticks(x + width * (len(model_names)-1) / 2)
ax.set_xticklabels(metric_cols, fontsize=11)
ax.set_ylim(0, 1.12)
ax.set_ylabel("Score")
ax.set_title("Model Performance Comparison — All Metrics", fontsize=14, fontweight='bold')
ax.legend(loc='upper right', fontsize=9)
ax.axhline(0.8, color='grey', linestyle='--', alpha=0.5)
plt.tight_layout()
plt.savefig("model_comparison_bar.png", dpi=150, bbox_inches='tight')
plt.show()

from sklearn.preprocessing import label_binarize
classes = sorted(y_test.unique())
y_test_bin = label_binarize(y_test, classes=classes)
fig, axes = plt.subplots(1, 2, figsize=(16, 6))
for (name, v), color in zip(results.items(), PALETTE):
    for i, cls in enumerate(classes):
        fpr, tpr, _ = roc_curve(y_test_bin[:, i], v['y_prob'][:, i])
        axes[0].plot(fpr, tpr, color=color, lw=1.2, alpha=0.55)
    axes[0].plot([], [], color=color, lw=2, label=f"{name} (AUC={v['roc_auc']:.3f})")
axes[0].plot([0,1],[0,1],'k--', alpha=0.4)
axes[0].set_xlabel("False Positive Rate")
axes[0].set_ylabel("True Positive Rate")
axes[0].set_title("ROC Curves (OvR) — All Models")
axes[0].legend(fontsize=9)
for (name, v), color in zip(results.items(), PALETTE):
    for i, cls in enumerate(classes):
        prec_arr, rec_arr, _ = precision_recall_curve(y_test_bin[:, i], v['y_prob'][:, i])
        axes[1].plot(rec_arr, prec_arr, color=color, lw=1.2, alpha=0.55)
    axes[1].plot([], [], color=color, lw=2, label=f"{name} (AP={v['avg_precision']:.3f})")
baseline = 1 / len(classes)
axes[1].axhline(baseline, color='gray', linestyle='--', alpha=0.6, label=f"Baseline ({baseline:.3f})")
axes[1].set_xlabel("Recall")
axes[1].set_ylabel("Precision")
axes[1].set_title("Precision-Recall Curves (OvR) — All Models")
axes[1].legend(fontsize=9)
plt.tight_layout()
plt.savefig("roc_pr_curves.png", dpi=150, bbox_inches='tight')
plt.show()

fig, axes = plt.subplots(2, 3, figsize=(17, 10))
class_labels = ['Budget', 'Mid-Range', 'Premium']
flat_axes = axes.flatten()
COLORMAPS = ['Blues', 'Greens', 'Oranges', 'Reds', 'Purples']
for i, ((name, v), cmap_choice) in enumerate(zip(results.items(), COLORMAPS)):
    ax = flat_axes[i]
    cm = v['confusion_matrix']
    disp = ConfusionMatrixDisplay(confusion_matrix=cm, display_labels=class_labels)
    disp.plot(ax=ax, colorbar=False, cmap=cmap_choice)
    ax.set_title(f"{name}\nF1={v['f1']:.3f}", fontsize=12, fontweight='bold')
    ax.set_xlabel("Predicted" if i >= 3 else "")
    ax.set_ylabel("Actual" if i % 3 == 0 else "")
flat_axes[-1].axis('off')
plt.suptitle("Confusion Matrices — Performance Overview", fontsize=16, fontweight='bold', y=0.95)
plt.tight_layout()
plt.show()

import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import matplotlib.gridspec as gridspec

from sklearn.manifold import TSNE
from sklearn.decomposition import PCA
from sklearn.calibration import calibration_curve
from sklearn.metrics import (
    roc_curve, auc,
    precision_recall_curve,
    confusion_matrix,
    classification_report
)
from sklearn.preprocessing import label_binarize
from scipy.cluster.hierarchy import linkage, dendrogram
from scipy.spatial.distance import pdist
from scipy.stats import entropy
sns.set_theme(style="whitegrid", context="talk")
plt.rcParams["figure.figsize"] = (16, 10)
classes = sorted(y_test.unique())
y_test_bin = label_binarize(y_test, classes=classes)
metric_cols = ['Accuracy', 'Precision', 'Recall', 'F1 Score', 'ROC-AUC']
metric_matrix = metrics_df[metric_cols].copy()
fig = plt.figure(figsize=(16, 10))
gs = gridspec.GridSpec(2, 2, width_ratios=[1, 4], height_ratios=[1, 4])
ax_col = plt.subplot(gs[0, 1])
col_linkage = linkage(pdist(metric_matrix.T), method='ward')
col_dendro = dendrogram(col_linkage, labels=metric_matrix.columns,
                        ax=ax_col, color_threshold=None)
ax_col.axis('off')
ax_row = plt.subplot(gs[1, 0])
row_linkage = linkage(pdist(metric_matrix), method='ward')
row_dendro = dendrogram(row_linkage, orientation='right',
                        labels=metric_matrix.index,
                        ax=ax_row, color_threshold=None)
ax_row.axis('off')
row_order = row_dendro['leaves']
col_order = col_dendro['leaves']
ax_heat = plt.subplot(gs[1, 1])
sns.heatmap(
    metric_matrix.iloc[row_order, col_order],
    annot=True,
    fmt=".3f",
    cmap="mako",
    linewidths=1,
    cbar_kws={'label': 'Metric Magnitude'},
    ax=ax_heat
)
ax_heat.set_title("Hierarchical Performance Landscape", fontsize=20, weight='bold')
plt.tight_layout()
plt.show()
fig, axes = plt.subplots(2, 3, figsize=(22, 12))
axes = axes.flatten()
for idx, (name, v) in enumerate(results.items()):
    ax = axes[idx]
    y_prob = v['y_prob']
    for i, cls in enumerate(classes):
        fpr, tpr, _ = roc_curve(y_test_bin[:, i], y_prob[:, i])
        roc_auc = auc(fpr, tpr)
        ax.plot(
            fpr,
            tpr,
            lw=2.5,
            label=f'{cls} (AUC={roc_auc:.3f})'
        )
    ax.plot([0, 1], [0, 1], '--', color='black', alpha=0.5)
    ax.set_title(name, fontsize=16, weight='bold')
    ax.set_xlabel("False Positive Rate")
    ax.set_ylabel("True Positive Rate")
    ax.legend(fontsize=9)
    ax.grid(alpha=0.3)
for j in range(idx + 1, len(axes)):
    axes[j].axis('off')
fig.suptitle("One-vs-Rest ROC Geometry Across Models", fontsize=24, weight='bold')
plt.tight_layout()
plt.show()
fig, axes = plt.subplots(2, 3, figsize=(22, 12))
axes = axes.flatten()
for idx, (name, v) in enumerate(results.items()):
    ax = axes[idx]
    probs = v['y_prob']
    for i, cls in enumerate(classes):
        frac_pos, mean_pred = calibration_curve(
            y_test_bin[:, i],
            probs[:, i],
            n_bins=10)
        ax.plot(
            mean_pred,
            frac_pos,
            marker='o',
            linewidth=2,
            label=cls)
    ax.plot([0, 1], [0, 1], '--', color='black', alpha=0.7)
    ax.set_title(name, fontsize=15, weight='bold')
    ax.set_xlabel("Mean Predicted Probability")
    ax.set_ylabel("Observed Frequency")
    ax.legend(fontsize=9)
    ax.grid(alpha=0.25)
for j in range(idx + 1, len(axes)):
    axes[j].axis('off')
fig.suptitle("Calibration Reliability Diagrams", fontsize=24, weight='bold')
plt.tight_layout()
plt.show()
entropy_scores = {}
fig, axes = plt.subplots(1, len(results), figsize=(28, 5))
for ax, (name, v) in zip(axes, results.items()):
    cm = v['confusion_matrix'].astype(float)
    cm_norm = cm / cm.sum(axis=1, keepdims=True)
    row_entropy = np.array([
        entropy(row + 1e-9, base=2)
        for row in cm_norm])
    entropy_scores[name] = row_entropy.mean()
    sns.heatmap(
        cm_norm,
        annot=True,
        fmt=".2f",
        cmap="rocket_r",
        square=True,
        linewidths=1,
        cbar=False,
        ax=ax)
    ax.set_title(
        f"{name}\nEntropy={entropy_scores[name]:.3f}",
        fontsize=14,
        weight='bold')
    ax.set_xlabel("Predicted")
    ax.set_ylabel("Actual")
fig.suptitle(
    "Normalized Confusion Entropy Analysis",
    fontsize=24,
    weight='bold')
plt.tight_layout()
plt.show()
best_model_name = metrics_df['F1 Score'].idxmax()
best_model = results[best_model_name]['model']
if hasattr(best_model, "predict_proba"):
    embedding_source = best_model.predict_proba(X_test_proc)
else:
    embedding_source = PCA(n_components=5).fit_transform(X_test_proc)
tsne = TSNE(
    n_components=2,
    perplexity=25,
    learning_rate='auto',
    init='pca',
    random_state=42)
embedding = tsne.fit_transform(embedding_source)
pred_labels = results[best_model_name]['y_pred']
fig, ax = plt.subplots(figsize=(14, 10))
scatter = ax.scatter(
    embedding[:, 0],
    embedding[:, 1],
    c=pd.factorize(pred_labels)[0],
    s=70,
    alpha=0.85
)
for cls in classes:
    idxs = np.where(pred_labels == cls)[0]
    ax.scatter([], [], label=cls)
ax.legend(title="Predicted Class")
ax.set_title(
    f"t-SNE Decision Geometry — {best_model_name}",
    fontsize=24,
    weight='bold'
)
ax.set_xlabel("Latent Dimension 1")
ax.set_ylabel("Latent Dimension 2")
ax.grid(alpha=0.25)
plt.tight_layout()
plt.show()
radar_metrics = metric_matrix.copy()
angles = np.linspace(
    0,
    2 * np.pi,
    len(radar_metrics.columns),
    endpoint=False
).tolist()
angles += angles[:1]
fig, ax = plt.subplots(figsize=(12, 12), subplot_kw=dict(polar=True))
for model_name in radar_metrics.index:
    values = radar_metrics.loc[model_name].tolist()
    values += values[:1]
    ax.plot(angles, values, linewidth=2.5, label=model_name)
    ax.fill(angles, values, alpha=0.08)
ax.set_xticks(angles[:-1])
ax.set_xticklabels(radar_metrics.columns, fontsize=14)
ax.set_ylim(0, 1.05)
ax.set_title(
    "Multi-Objective Model Performance Topology",
    fontsize=24,
    weight='bold',
    pad=30
)
ax.legend(
    loc='upper right',
    bbox_to_anchor=(1.25, 1.10),
    fontsize=11
)
plt.tight_layout()
plt.show()
fig, axes = plt.subplots(2, 3, figsize=(22, 12))
axes = axes.flatten()
for idx, (name, v) in enumerate(results.items()):
    ax = axes[idx]
    probs = v['y_prob']
    for i, cls in enumerate(classes):
        precision, recall, _ = precision_recall_curve(
            y_test_bin[:, i],
            probs[:, i]
        )
        pr_auc = auc(recall, precision)
        ax.plot(
            recall,
            precision,
            linewidth=2.5,
            label=f'{cls} (AUC={pr_auc:.3f})'
        )
    ax.set_title(name, fontsize=15, weight='bold')
    ax.set_xlabel("Recall")
    ax.set_ylabel("Precision")
    ax.legend(fontsize=9)
    ax.grid(alpha=0.3)
for j in range(idx + 1, len(axes)):
    axes[j].axis('off')
fig.suptitle(
    "Precision-Recall Dominance Frontiers",
    fontsize=24,
    weight='bold'
)
plt.tight_layout()
plt.show()
stability_df = pd.DataFrame({
    'Model': metrics_df.index,
    'CV_F1': metrics_df['CV F1 (5-fold)'],
    'Test_F1': metrics_df['F1 Score']
})
stability_df['Generalization_Gap'] = (
    stability_df['CV_F1'] - stability_df['Test_F1']
).abs()
fig, ax = plt.subplots(figsize=(14, 8))
scatter = ax.scatter(
    stability_df['CV_F1'],
    stability_df['Test_F1'],
    s=700 * (1 - stability_df['Generalization_Gap'] + 0.05),
    alpha=0.7
)
for i, row in stability_df.iterrows():
    ax.text(
        row['CV_F1'] + 0.002,
        row['Test_F1'] + 0.002,
        row['Model'],
        fontsize=12,
        weight='bold'
    )
ax.plot([0, 1], [0, 1], '--', color='black')
ax.set_title(
    "Generalization Stability Manifold",
    fontsize=24,
    weight='bold'
)
ax.set_xlabel("Cross-Validated F1")
ax.set_ylabel("Test F1")
ax.grid(alpha=0.3)
plt.tight_layout()
plt.show()

radar_metrics = ['Accuracy', 'Precision', 'Recall', 'F1 Score', 'ROC-AUC']
N = len(radar_metrics)
angles = [n / float(N) * 2 * np.pi for n in range(N)]
angles += angles[:1]
fig, ax = plt.subplots(figsize=(8, 8), subplot_kw=dict(polar=True))
ax.set_facecolor('#f8f9fa')
for (name, _), color in zip(results.items(), PALETTE):
    vals = [metrics_df.loc[name, m] for m in radar_metrics]
    vals += vals[:1]
    ax.plot(angles, vals, 'o-', linewidth=2, label=name, color=color)
    ax.fill(angles, vals, alpha=0.07, color=color)
ax.set_xticks(angles[:-1])
ax.set_xticklabels(radar_metrics, fontsize=11)
ax.set_ylim(0, 1)
ax.set_yticks([0.2, 0.4, 0.6, 0.8, 1.0])
ax.set_yticklabels(['0.2','0.4','0.6','0.8','1.0'], fontsize=8)
ax.set_title("Radar Chart — Model Performance", fontsize=14, fontweight='bold', pad=20)
ax.legend(loc='upper right', bbox_to_anchor=(1.35, 1.1), fontsize=10)
plt.tight_layout()
plt.savefig("radar_chart.png", dpi=150, bbox_inches='tight')
plt.show()

"""## 8. Best Model Deep Dive <a id='8-best-model'></a>"""

best_model_name = metrics_df['F1 Score'].idxmax()
best = results[best_model_name]
best_model_obj = best['model']
print(f" BEST PRICE RANGE MODEL: {best_model_name}")
for metric in ['accuracy', 'precision', 'recall', 'f1', 'roc_auc', 'avg_precision', 'cv_f1']:
    print(f"  {metric:<25} {best[metric]:.4f}")
print("\n Classification Report")
print(classification_report(y_test, best['y_pred'],target_names=['Budget', 'Mid-Range', 'Premium']))

train_sizes, train_scores, val_scores = learning_curve(
    best_model_obj, X_train_bal, y_train_bal,
    cv=5, scoring='f1_weighted',
    train_sizes=np.linspace(0.1, 1.0, 10),
    n_jobs=-1)
train_mean = train_scores.mean(axis=1)
train_std  = train_scores.std(axis=1)
val_mean   = val_scores.mean(axis=1)
val_std    = val_scores.std(axis=1)
fig, ax = plt.subplots(figsize=(10, 5))
ax.plot(train_sizes, train_mean, 'o-', color=PALETTE[0], lw=2, label="Training F1")
ax.fill_between(train_sizes, train_mean - train_std, train_mean + train_std,
                alpha=0.15, color=PALETTE[0])
ax.plot(train_sizes, val_mean, 's-', color=PALETTE[1], lw=2, label="Validation F1")
ax.fill_between(train_sizes, val_mean - val_std, val_mean + val_std,
                alpha=0.15, color=PALETTE[1])
ax.set_xlabel("Training Set Size")
ax.set_ylabel("F1 Score")
ax.set_title(f"Learning Curve — {best_model_name}", fontsize=13, fontweight='bold')
ax.legend()
plt.tight_layout()
plt.savefig("learning_curve.png", dpi=150, bbox_inches='tight')
plt.show()

from sklearn.preprocessing import label_binarize
classes = sorted(y_test.unique())
y_test_bin = label_binarize(y_test, classes=classes)
fig, axes = plt.subplots(1, len(classes), figsize=(15, 4))
for i, (cls, ax) in enumerate(zip(classes, axes)):
    prec_arr, rec_arr, thresholds = precision_recall_curve(
        y_test_bin[:, i], best['y_prob'][:, i])
    f1_scores_thresh = 2 * prec_arr * rec_arr / (prec_arr + rec_arr + 1e-9)
    opt_idx = np.argmax(f1_scores_thresh[:-1])
    opt_thresh = thresholds[opt_idx]
    opt_f1 = f1_scores_thresh[opt_idx]
    ax.plot(thresholds, f1_scores_thresh[:-1], color=PALETTE[i], lw=2)
    ax.axvline(opt_thresh, color=PALETTE[1], linestyle='--', lw=1.8,
               label=f"Opt={opt_thresh:.3f} (F1={opt_f1:.3f})")
    ax.axvline(0.5, color='gray', linestyle=':', lw=1.5, label="Default=0.5")
    ax.set_xlabel("Threshold")
    ax.set_ylabel("F1 Score")
    ax.set_title(f"Threshold vs F1\n[{cls}]")
    ax.legend(fontsize=8)
plt.suptitle(f"Per-Class Threshold Optimisation — {best_model_name}",
             fontsize=13, fontweight='bold')
plt.tight_layout()
plt.savefig("threshold_optimisation.png", dpi=150, bbox_inches='tight')
plt.show()

"""## 9. Conclusions <a id='9-conclusions'></a>"""

final_rank = metrics_df[['Accuracy','Precision','Recall','F1 Score','ROC-AUC',
                           'CV F1 (5-fold)']].sort_values('F1 Score', ascending=False)
display(final_rank.style
        .background_gradient(cmap='RdYlGn', axis=0)
        .format("{:.4f}")
        .highlight_max(color='#000000', axis=0)
        .set_caption("Green = best per column"))

print(f"WINNER: {best_model_name}")
print(f" F1 Score: {metrics_df.loc[best_model_name,'F1 Score']:.4f}")
print(f" ROC-AUC: {metrics_df.loc[best_model_name,'ROC-AUC']:.4f}")
print(f" CV F1: {metrics_df.loc[best_model_name,'CV F1 (5-fold)']:.4f}")

import pickle
import os
save_payload = {
    'model':       best_model_obj,
    'preprocessor': preprocessor,
    'classes':     list(results[best_model_name]['model'].classes_),
    'model_name':  best_model_name,
    'features': {
        'numerical':   NUMERICAL_FEATURES,
        'categorical': CATEGORICAL_FEATURES,
        'binary':      BINARY_FEATURES,
    }
}
with open('ram_price_model.pkl', 'wb') as f:
    pickle.dump(save_payload, f)
print(f"✓ Saved: ram_price_model.pkl  ({os.path.getsize('ram_price_model.pkl') / 1024:.1f} KB)")

"""### Key Findings

| Finding | Detail |
|---------|--------|
| **Best Model** | Determined by highest F1 on the held-out test set |
| **Class Imbalance** | Addressed via SMOTE on training data only |
| **Most Predictive Features** | `log_price`, `capacity_gb`, `is_ecc`, `price_per_gb`, `ram_generation` |
| **Model Architecture** | All pipelines: Impute → Scale → Encode → Classify |
| **Hyperparameter Tuning** | GridSearchCV with 5-fold stratified CV, optimised for F1 |

### Recommendations

1. **Deploy the winning model** behind a lightweight REST API for real-time listing classification.
2. **Threshold tuning** — the optimal decision threshold often differs from 0.5 for imbalanced problems; use the PR-AUC curve to set production thresholds based on business cost of FP vs FN.
3. **Feature additions** — title NLP embeddings (TF-IDF / BERT) on the product title could further improve accuracy.
4. **Monitoring** — retrain quarterly as RAM product lines (DDR6 etc.) emerge.

---
*Analysis completed · RAM Pricing Intelligence 2026*
"""